package main

import (
	"fmt"
	"strings"
)

// render turns the probe results into docs/conformance.md.
//
// The output carries no timestamp, no host name and no version string, so that
// regenerating it on an unchanged tree produces an unchanged file. That is what
// lets `conformance builtins -check` be a build step: the document either
// matches the code or the build says so.
func render(rows []row) string {
	var b strings.Builder
	missingRows := filter(rows, func(r row) bool { return r.self == missing })
	unknownRows := filter(rows, func(r row) bool { return r.self == unknown })
	bootMissingRows := filter(rows, func(r row) bool { return r.boot == missing })

	b.WriteString("# Builtin conformance\n\n")
	b.WriteString("Generated by `make conformance`. Do not edit by hand.\n\n")
	b.WriteString("Twill has two implementations. The Go bootstrap under `internal/` is the\n")
	b.WriteString("reference. The self-hosted implementation under `src/` is twill written in\n")
	b.WriteString("twill. `src/builtins.tw` holds the one table of builtin names that the\n")
	b.WriteString("self-hosted checker and evaluator share, so a name in it type-checks on both\n")
	b.WriteString("sides whether or not either side can run it.\n\n")
	b.WriteString("This file says which of those names each implementation actually evaluates.\n")
	b.WriteString("Every row is measured, not declared: the tool calls the builtin on both\n")
	b.WriteString("implementations and reads the answer out of what came back. A name is\n")
	b.WriteString("unimplemented self-hosted when `src/eval.tw` reaches the end of its dispatch\n")
	b.WriteString("chain and reports \"named in the builtin table but has no implementation\", and\n")
	b.WriteString("unimplemented on the bootstrap when the Go interpreter has no such variable\n")
	b.WriteString("bound at all.\n\n")
	b.WriteString("The question is what `src/eval.tw` can run **for a program it is given**, which\n")
	b.WriteString("is not the same question as what the self-hosted compiler itself uses. Every\n")
	b.WriteString("name here is available to `src/*.tw` while the Go bootstrap is executing it, so\n")
	b.WriteString("`write_out` can be in the list below and still be how `src/main.tw` prints.\n\n")

	b.WriteString("## Summary\n\n")
	b.WriteString("| | count |\n|---|---|\n")
	fmt.Fprintf(&b, "| names in the shared table | %d |\n", len(rows))
	fmt.Fprintf(&b, "| implemented by the Go bootstrap | %d |\n",
		countBy(rows, func(r row) bool { return r.boot == present }))
	fmt.Fprintf(&b, "| implemented by the self-hosted evaluator | %d |\n",
		countBy(rows, func(r row) bool { return r.self == present }))
	fmt.Fprintf(&b, "| **missing from the self-hosted evaluator** | **%d** |\n", len(missingRows))
	fmt.Fprintf(&b, "| missing from the Go bootstrap | %d |\n", len(bootMissingRows))
	fmt.Fprintf(&b, "| inconclusive (see below) | %d |\n\n", len(unknownRows))

	b.WriteString("## Missing from the self-hosted evaluator\n\n")
	if len(missingRows) == 0 {
		b.WriteString("None. The two evaluators cover the same table.\n\n")
	} else {
		b.WriteString("Calling one of these on `src/main.tw` is a runtime error, not a wrong\n")
		b.WriteString("answer. They are listed here so that \"the two implementations agree\" can be\n")
		b.WriteString("read as the bounded claim it is.\n\n")
		writeNames(&b, names(missingRows))
	}

	if len(bootMissingRows) > 0 {
		b.WriteString("## Missing from the Go bootstrap\n\n")
		writeNames(&b, names(bootMissingRows))
	}

	if len(unknownRows) > 0 {
		b.WriteString("## Inconclusive\n\n")
		b.WriteString("The probe could not get the call as far as a plain yes or no on one side\n")
		b.WriteString("or the other, so no claim is made about these names. The usual cause is the\n")
		b.WriteString("self-hosted evaluator failing inside its own source rather than reporting a\n")
		b.WriteString("fault in the program it was given, which means the name is dispatched but its\n")
		b.WriteString("implementation is broken. The evidence column says what came back.\n\n")
		b.WriteString("| builtin | bootstrap | self-hosted | evidence |\n|---|---|---|---|\n")
		for _, r := range unknownRows {
			ev := r.selfEvidence
			if r.self != unknown {
				ev = r.bootEvidence
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", r.name, r.boot, r.self, cell(ev))
		}
		b.WriteString("\n")
	}

	b.WriteString("## Every name\n\n")
	b.WriteString("| builtin | bootstrap | self-hosted |\n|---|---|---|\n")
	for _, r := range rows {
		fmt.Fprintf(&b, "| `%s` | %s | %s |\n", r.name, r.boot, r.self)
	}
	return b.String()
}

// writeNames prints a list of names in fixed-width columns, which is shorter to
// read than a one-row-per-name table when the only fact is membership.
func writeNames(b *strings.Builder, ns []string) {
	const cols = 4
	b.WriteString("```\n")
	width := 0
	for _, n := range ns {
		if len(n) > width {
			width = len(n)
		}
	}
	for i, n := range ns {
		if i%cols == cols-1 || i == len(ns)-1 {
			b.WriteString(n + "\n")
			continue
		}
		b.WriteString(n + strings.Repeat(" ", width+2-len(n)))
	}
	b.WriteString("```\n\n")
}

func filter(rows []row, pred func(row) bool) []row {
	var out []row
	for _, r := range rows {
		if pred(r) {
			out = append(out, r)
		}
	}
	return out
}

func names(rows []row) []string {
	out := make([]string, len(rows))
	for i, r := range rows {
		out[i] = r.name
	}
	return out
}

// cell makes a string safe to put in a markdown table cell.
func cell(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	if len(s) > 120 {
		s = s[:120] + "..."
	}
	return s
}
